// Package defaults provides default configuration values.
package defaults

const (
	DefaultModel    = "deepseek/deepseek-chat"
	DefaultProvider = "deepseek"
	MaxTurns        = 10
	MaxTokens       = 8192
	Temperature     = 0.7
)

// Attribution returns the provider attribution text.
func Attribution(provider, model string) string {
	return "Generated by pi-go ● " + provider + "/" + model
}
